name: planza
description: "Planza is a task management app designed to help users stay organized and achieve their goals effectively. With features like task creation, goal setting, and calendar integration, Planza offers a flexible and intuitive approach to managing daily activities."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  riverpod: ^2.6.1
  dio: ^5.8.0+1
  shared_preferences: ^2.5.2
  sqflite: ^2.4.1
  get_it: ^8.0.3
  intl: ^0.19.0
  drift: ^2.25.1
  path_provider: ^2.1.5
  drift_flutter: ^0.2.4
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  easy_date_timeline: ^2.0.9
  dot_navigation_bar: ^1.0.2
  http: ^1.3.0
  curved_navigation_bar: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  drift_dev: ^2.25.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lang/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700